/**
 * PharmaTrace Supply Chain Information Network API
 * The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: api@pharmatrace.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.pharmatrace.api.scin.public.model


case class Stakeholder (
  // unique official register entry, e.g. Handelsregistereintrag, court number, ...
  tradeId: Option[String] = None,
  // type of the official register that has issued the trade id
  tradeIdType: Option[String] = None,
  // display name visible to other network members
  displayName: Option[String] = None,
  // one of Manufacturer, Distributor, Pharmacy, Regulator, Hospital, MedicalPractice, CareProvider, DisposalFirm, Insurance, Patient, LawEnforcement
  stakeholderRole: Option[String] = None,
  // id of the main wallet, which the stakeholder uses for PT token transactions with other stakeholders
  walletId: Option[String] = None
)

