/**
 * PharmaTrace Supply Chain Information Network API
 * The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: api@pharmatrace.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model


case class Container (
  // Unique identifier representing a specific container.
  containerId: Option[String] = None,
  // EPC code
  epcCode: Option[String] = None,
  // Serialization label.
  label: Option[String] = None,
  // barcode on container. Normally equal to container id.
  barcode: Option[String] = None,
  // RFID of RF tracking label on conatiner.
  rfId: Option[String] = None,
  // quantity of product in container.
  quantity: Option[Number] = None,
  // Unit for quantity measurement.
  unit: Option[String] = None,
  // Location id of last tracked locaction.
  currentLocationId: Option[String] = None,
  // stakeholder id of the last tracked owner of the container.
  ownerStakeholderId: Option[String] = None,
  // id of the parent container or null.
  parentContainerId: Option[String] = None
)

