/**
 * PharmaTrace Supply Chain Information Network API
 * The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: api@pharmatrace.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model


case class Profile (
  // First name of the PT network user.
  firstName: Option[String] = None,
  // Last name of the PT network user.
  lastName: Option[String] = None,
  // Email address
  email: Option[String] = None,
  // Twitter name
  twitterName: Option[String] = None,
  // LinkedIn name
  linkedinName: Option[String] = None,
  // Facebook name
  facebookName: Option[String] = None,
  // Image URL
  picture: Option[String] = None,
  // the PT network member that the user/profile is assigned to.
  stakeholderId: Option[String] = None,
  // true if the user is currently active. Inactive users will be anonymized but not deleted to maintain integrity of transaction history
  active: Option[Boolean] = None
)

